jobs:
  - job: ubuntu_1604
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        python36:
          python.version: '3.6'
          build.type: 'Debug'
          sanitizer: 'ON'
          static: 'OFF'
        Python27:
          python.version: '2.7'
          build.type: 'Release'
          sanitizer: 'OFF'
          static: 'ON'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          addToPath: true
      - script: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$(build.type) -SANITIZER=$(sanitizer) -DSTATIC_BUILD=$(static)
          make simple_test -j `nproc`
  
  - job: macos_latest
    pool:
      vmImage: 'macos-latest'
    steps:
      - script: |
          brew install cmake gcc@9 zlib bzip2
      - script: |
          mkdir build
          cd build
          CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=debug -SANITIZER=ON ..
          make simple_test -j `sysctl -n hw.physicalcpu`

  - job: macos_1013
    pool:
      vmImage: 'macos-10.13'
    steps:
      - script: |
          brew install cmake gcc@9 zlib bzip2
      - script: |
          mkdir build
          cd build
          CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=debug -SANITIZER=ON ..
          make simple_test -j `sysctl -n hw.physicalcpu`