jobs:
  - job: ubuntu_1604
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        python36:
          python.version: '3.6'
          build.type: 'Debug'
          sanitizer: 'ON'
          static: 'OFF'
        Python27:
          python.version: '2.7'
          build.type: 'Release'
          sanitizer: 'OFF'
          static: 'ON'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          addToPath: true
      - script: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$(build.type) -SANITIZER=$(sanitizer) -DSTATIC_BUILD=$(static)
          make simple_test -j `nproc`
        displayName: 'build and test'

  - job: macos
    strategy:
      matrix:
        os1013:
          image: macos-10.13
        latest:
          image: macos-latest
    pool:
      vmImage: $(image)
    steps:
      - script: |
          brew install cmake gcc@9 zlib bzip2
        displayName: 'install dependencies'
      - script: |
          mkdir build
          cd build
          CC=gcc-9 CXX=g++-9 cmake ..
          make simple_test -j `sysctl -n hw.physicalcpu`
        displayName: 'build and test'
